package com.Diseño;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author frany
 */
public class DiseñoParaEstudiante extends javax.swing.JFrame {

    //Objetos necesarios para la conexión a la base de datos
    //En este objeto se almacena la ubicación del archivo donde se encuetra la base de datos.
    String url = "jdbc:sqlite:C:\\Diseño\\src\\BaseDeDatos\\BDProyecto.db";
    //Objeto necesario para realizar la conexión.
    Connection connect;

    /**
     * Creates new form Diseño
     */
    public DiseñoParaEstudiante() {
        initComponents();

        //Hace que el Jframe inicie en el centro de la pantalla
        this.setLocationRelativeTo(this);
        //Metodo para Mostar los datos en el Jtable
        mostrarDatos();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Exitbtn = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        Perfil1 = new javax.swing.JLabel();
        Usuario1 = new javax.swing.JLabel();
        Rol1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Matricula = new javax.swing.JLabel();
        IngreMatricula = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        IngreNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Nombre = new javax.swing.JLabel();
        IngreApellido = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        IngreCorreo = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        Materia = new javax.swing.JLabel();
        IngreMateria = new javax.swing.JTextField();
        LimpiarPanel = new javax.swing.JPanel();
        Limpiarbtn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PanelBuscar = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JLabel();
        PanelListar = new javax.swing.JPanel();
        btnListar = new javax.swing.JLabel();
        Buscar = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        Filtro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diseño");
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        Exitbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitbtnMouseClicked(evt);
            }
        });

        lblMinimizar.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar.setText("−");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseExited(evt);
            }
        });

        Perfil1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario2.png"))); // NOI18N
        Perfil1.setText("jLabel1");

        Usuario1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Usuario1.setForeground(new java.awt.Color(255, 255, 255));
        Usuario1.setText("Usuario");

        Rol1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Rol1.setForeground(new java.awt.Color(255, 255, 255));
        Rol1.setText("Rol");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Perfil1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rol1)
                    .addComponent(Usuario1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 787, Short.MAX_VALUE)
                .addComponent(lblMinimizar)
                .addGap(18, 18, 18)
                .addComponent(Exitbtn)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(Exitbtn))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(Usuario1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Rol1)
                                    .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Perfil1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setEnabled(false);

        Matricula.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Matricula.setText("Matricula");

        IngreMatricula.setEditable(false);
        IngreMatricula.setBackground(new java.awt.Color(255, 51, 51));
        IngreMatricula.setForeground(new java.awt.Color(204, 204, 204));
        IngreMatricula.setText("Ingrese la matricula");
        IngreMatricula.setBorder(null);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        IngreNombre.setEditable(false);
        IngreNombre.setBackground(new java.awt.Color(255, 51, 51));
        IngreNombre.setForeground(new java.awt.Color(204, 204, 204));
        IngreNombre.setText("Ingrese el nombre");
        IngreNombre.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        Nombre.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Nombre.setText("Nombre");

        IngreApellido.setEditable(false);
        IngreApellido.setBackground(new java.awt.Color(255, 51, 51));
        IngreApellido.setForeground(new java.awt.Color(204, 204, 204));
        IngreApellido.setText("Ingrese el apellido");
        IngreApellido.setBorder(null);

        Apellido.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Apellido.setText("Apellido");

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        IngreCorreo.setEditable(false);
        IngreCorreo.setBackground(new java.awt.Color(255, 51, 51));
        IngreCorreo.setForeground(new java.awt.Color(204, 204, 204));
        IngreCorreo.setText("Ingrese el correo");
        IngreCorreo.setBorder(null);

        Correo.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Correo.setText("Correo");

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        Materia.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Materia.setText("Materia");

        IngreMateria.setEditable(false);
        IngreMateria.setBackground(new java.awt.Color(255, 51, 51));
        IngreMateria.setForeground(new java.awt.Color(204, 204, 204));
        IngreMateria.setText("Ingrese la materia");
        IngreMateria.setBorder(null);

        LimpiarPanel.setBackground(java.awt.Color.gray);

        Limpiarbtn.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        Limpiarbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Limpiarbtn.setText("LIMPIAR");
        Limpiarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Limpiarbtn.setFocusable(false);
        Limpiarbtn.setMaximumSize(new java.awt.Dimension(32767, 32767));
        Limpiarbtn.setMinimumSize(new java.awt.Dimension(100, 100));
        Limpiarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LimpiarbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LimpiarbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LimpiarbtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout LimpiarPanelLayout = new javax.swing.GroupLayout(LimpiarPanel);
        LimpiarPanel.setLayout(LimpiarPanelLayout);
        LimpiarPanelLayout.setHorizontalGroup(
            LimpiarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LimpiarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Limpiarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LimpiarPanelLayout.setVerticalGroup(
            LimpiarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LimpiarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Limpiarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(LimpiarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Matricula)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(IngreMatricula)
                                .addComponent(jSeparator1)
                                .addComponent(IngreNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                .addComponent(jSeparator2)
                                .addComponent(Nombre)
                                .addComponent(IngreApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                .addComponent(Apellido)
                                .addComponent(jSeparator3)
                                .addComponent(IngreCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                .addComponent(Correo)
                                .addComponent(jSeparator4)
                                .addComponent(jSeparator5)
                                .addComponent(Materia)
                                .addComponent(IngreMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Matricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Apellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Correo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Materia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(LimpiarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        Bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 290, 620));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        PanelBuscar.setBackground(java.awt.Color.gray);

        btnBuscar.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelBuscarLayout = new javax.swing.GroupLayout(PanelBuscar);
        PanelBuscar.setLayout(PanelBuscarLayout);
        PanelBuscarLayout.setHorizontalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        PanelBuscarLayout.setVerticalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        PanelListar.setBackground(java.awt.Color.gray);

        btnListar.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        btnListar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnListar.setText("Listar");
        btnListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelListarLayout = new javax.swing.GroupLayout(PanelListar);
        PanelListar.setLayout(PanelListarLayout);
        PanelListarLayout.setHorizontalGroup(
            PanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        PanelListarLayout.setVerticalGroup(
            PanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        Buscar.setBackground(new java.awt.Color(0, 0, 0));
        Buscar.setForeground(new java.awt.Color(102, 102, 102));
        Buscar.setText("Ingresar dato");
        Buscar.setBorder(null);
        Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscarMousePressed(evt);
            }
        });
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Filtro.setBackground(new java.awt.Color(0, 0, 0));
        Filtro.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Filtro.setForeground(new java.awt.Color(255, 255, 255));
        Filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mostrar todo", "Matricula", "Nombre", "Apellido", "Correo", "Materia" }));
        Filtro.setAutoscrolls(true);
        Filtro.setBorder(null);
        Filtro.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(PanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Buscar)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Filtro, 0, 113, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(PanelListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        Bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 710, 140));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nombre", "Apellido", "Correo", "Materia"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        Bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 680, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Bg, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LimpiarbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarbtnMouseEntered
        //Cambia el color a rojo cuando el mouse se posa encima
        LimpiarPanel.setBackground(Color.red);
    }//GEN-LAST:event_LimpiarbtnMouseEntered

    private void LimpiarbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarbtnMouseExited
       //Cambia el color a gris cuando el mouse ya no se encuentra encima
        LimpiarPanel.setBackground(Color.gray);
    }//GEN-LAST:event_LimpiarbtnMouseExited
//Boton para cerrar el programa o volver a la pantalla de inicio
    private void ExitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitbtnMouseClicked
        int seleccion = JOptionPane.showOptionDialog(null, "¿Estás seguro de que quieres cerrar sesión?",
                "Cerrar Sesión", JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE, null,
                new Object[]{"Si", "No", "Salir del programa"}, "opcion 1");

        if (seleccion == 0) {
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        }
        if (seleccion == 2) {
            System.exit(0);
        }


    }//GEN-LAST:event_ExitbtnMouseClicked

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        //Cambia el color del botón a azul cuando el cursos se posa encima
        PanelBuscar.setBackground(Color.blue);
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        //Cambia el color del botón a gris cuando el cursor no se encuentra encima
        PanelBuscar.setBackground(Color.gray);
    }//GEN-LAST:event_btnBuscarMouseExited
//Limpia todas las cajas de texto
    private void LimpiarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarbtnMouseClicked
        IngreMatricula.setText("Ingrese la matricula");
        IngreMatricula.setForeground(Color.LIGHT_GRAY);
        IngreNombre.setText("Ingrese el nombre");
        IngreNombre.setForeground(Color.LIGHT_GRAY);
        IngreApellido.setText("Ingrese el apellido");
        IngreApellido.setForeground(Color.LIGHT_GRAY);
        IngreCorreo.setText("Ingrese el correo");
        IngreCorreo.setForeground(Color.LIGHT_GRAY);
        IngreMateria.setText("Ingrese la materia");
        IngreMateria.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_LimpiarbtnMouseClicked
//Minimiza el la ventana
    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseEntered
        //Cambia el color del boton a gris cuando el mouse se encuentra encima
        lblMinimizar.setForeground(Color.gray);
    }//GEN-LAST:event_lblMinimizarMouseEntered

    private void lblMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseExited
        //Cambia el color del boton a blanco cuando el mouse no se encuentra encima
        lblMinimizar.setForeground(Color.white);
    }//GEN-LAST:event_lblMinimizarMouseExited
    //Variables de tipo entero donde se almacenará la posición del mouse.
    int xx, xy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        //Obtendrá la posición X e Y del mouse cuando la presionemos
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        //Obtendrá la posición X e Y de la pantalla
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        //Restar la posción del a pantalla con la posición del mouse.
        setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void BuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarMousePressed
        //Da efecto de PlaceHolder a la caja de texto.
        if (IngreMatricula.getText().isEmpty()) {
            IngreMatricula.setText("Ingrese la matricula");
            IngreMatricula.setForeground(Color.LIGHT_GRAY);
        }
        if (IngreNombre.getText().isEmpty()) {
            IngreNombre.setText("Ingrese el nombre");
            IngreNombre.setForeground(Color.LIGHT_GRAY);
        }
        if (IngreApellido.getText().isEmpty()) {
            IngreApellido.setText("Ingrese el apellido");
            IngreApellido.setForeground(Color.LIGHT_GRAY);
        }
        if (IngreCorreo.getText().isEmpty()) {
            IngreCorreo.setText("Ingrese el correo");
            IngreCorreo.setForeground(Color.LIGHT_GRAY);
        }
        if (IngreMateria.getText().isEmpty()) {
            IngreMateria.setText("Ingrese la materia");
            IngreMateria.setForeground(Color.LIGHT_GRAY);
        }
        if (Buscar.getText().equals("Ingresar dato")) {
            Buscar.setText("");
            Buscar.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_BuscarMousePressed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaMouseClicked

//Reliza la busqueda
    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        if (!Buscar.getText().isEmpty()) {

            conectar();

            String busqueda = Buscar.getText().toString();
            String variable;

            if (Filtro.getSelectedIndex() == 0) {

                JOptionPane.showMessageDialog(this, "Debe seleccionar otra opcion");
            } else if (Filtro.getSelectedIndex() == 1) {
                variable = "Matricula";
                try {
                    MostrarBuscador(busqueda, variable);

                } catch (Exception e) {
                }
            } else if (Filtro.getSelectedIndex() == 2) {
                variable = "Nombre";
                try {
                    MostrarBuscador(busqueda, variable);

                } catch (Exception e) {
                }
            } else if (Filtro.getSelectedIndex() == 3) {
                variable = "Apellido";
                try {
                    MostrarBuscador(busqueda, variable);

                } catch (Exception e) {
                }
            } else if (Filtro.getSelectedIndex() == 4) {
                variable = "Correo";
                try {
                    MostrarBuscador(busqueda, variable);

                } catch (Exception e) {
                }
            } else if (Filtro.getSelectedIndex() == 5) {
                variable = "Materia";
                try {
                    MostrarBuscador(busqueda, variable);

                } catch (Exception e) {
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Tiene que ingresar un dato");

        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarMouseClicked
        //Método que sirve para mostrar los datos en la tabla
        mostrarDatos();
    }//GEN-LAST:event_btnListarMouseClicked

    private void btnListarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarMouseEntered
        //Cambia el oclor del fondo a verde cuando el mouse está encima||
        PanelListar.setBackground(Color.green);
    }//GEN-LAST:event_btnListarMouseEntered

    private void btnListarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarMouseExited
        //Cambia el color del fondo a gris cuando el mouse no están encima
        PanelListar.setBackground(Color.gray);
    }//GEN-LAST:event_btnListarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiseñoParaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiseñoParaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiseñoParaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiseñoParaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiseñoParaEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JPanel Bg;
    private javax.swing.JTextField Buscar;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Exitbtn;
    private javax.swing.JComboBox<String> Filtro;
    private javax.swing.JTextField IngreApellido;
    private javax.swing.JTextField IngreCorreo;
    private javax.swing.JTextField IngreMateria;
    private javax.swing.JTextField IngreMatricula;
    private javax.swing.JTextField IngreNombre;
    private javax.swing.JPanel LimpiarPanel;
    private javax.swing.JLabel Limpiarbtn;
    private javax.swing.JLabel Materia;
    private javax.swing.JLabel Matricula;
    private javax.swing.JLabel Nombre;
    private javax.swing.JPanel PanelBuscar;
    private javax.swing.JPanel PanelListar;
    private javax.swing.JLabel Perfil1;
    public javax.swing.JLabel Rol1;
    private javax.swing.JTable Tabla;
    public javax.swing.JLabel Usuario1;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnListar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblMinimizar;
    // End of variables declaration//GEN-END:variables

    //Muestra los datos en la tabla
    private void mostrarDatos() {
        //Método que realiza la conexión a la base de datos
        conectar();

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Matricula");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Correo");
        modelo.addColumn("Materia");
        Tabla.setModel(modelo);
        String consultaSql = "select * from Estudiante";
        String data[] = new String[7];

        Statement st;

        try {
            st = (Statement) connect.createStatement();
            ResultSet rs = st.executeQuery(consultaSql);
            while (rs.next()) {
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);
                data[3] = rs.getString(4);
                data[4] = rs.getString(5);
                data[5] = rs.getString(6);
                modelo.addRow(data);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error en la consulta: " + ex);
        }
    }

    //Conexión a la base de datos.
    public Connection conectar() {
        try {
            connect = DriverManager.getConnection(url);

        } catch (Exception x) {
            JOptionPane.showMessageDialog(null, x.getMessage().toString());

        }
        return connect;
    }
    
    //Mostrar resultados de la busqueda en la tabla
    public void MostrarBuscador(String busqueda, String variable) {
        //Método que realiza la conexión a la base de datos
        conectar();
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Matricula");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Correo");
        modelo.addColumn("Materia");
        Tabla.setModel(modelo);
        String consultaSql = "select * from Estudiante where " + variable + " like '%" + busqueda + "%' ";
        String data[] = new String[7];

        Statement st;
        ResultSet rs = null;
        try {
            st = (Statement) connect.createStatement();
            rs = st.executeQuery(consultaSql);
            while (rs.next()) {
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);
                data[3] = rs.getString(4);
                data[4] = rs.getString(5);
                data[5] = rs.getString(6);
                modelo.addRow(data);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error en la consulta: " + ex);
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);

            }

        }
    }

}
