/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Diseño;

import java.awt.Color;
import java.awt.Image;
import java.sql.*;
import java.util.Set;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author frany
 */
public class Login extends javax.swing.JFrame {
    //Objetos necesarios para la conexión a la base de datos
    //En este objeto se almacena la ubicación del archivo donde se encuetra la base de datos.
    String url = "jdbc:sqlite:C:\\Diseño\\src\\BaseDeDatos\\BDProyecto.db";
    //Objeto necesario para realizar la conexión.
    Connection connect;
    //Variable que sirve para almacenar la cantidad de intentos fallidos al iniciar sesión.
    int intentos = 0;

    /**
     * Creates new form Login
     */
    public Login() {
        //Quitar la botonera superior que traen por defectos las ventanas.
        setUndecorated(true);
        //Sirve para dar color al fondo, en este caso se utilizó para reducir la opacidad.
        setBackground(new Color(0, 0, 0, 220));

        initComponents();
        //Hace que el panel principal sea transparente
        PanelPrincipal.setOpaque(false);
        //Reducir la opacidad de estos 3 elementos.
        IngreUsuario.setBackground(new java.awt.Color(0, 0, 0, 1));
        IngreContraseña.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtRegistrarse.setBackground(new java.awt.Color(0, 0, 0, 1));

        //Hace que el Jframe inicie en el centro de la pantalla
        this.setLocationRelativeTo(this);

        //Sirve para poder ajustar el tamaño de la imagen dentro de un JLabel
        ImageIcon imagen = new ImageIcon(getClass().getResource("/Imagenes/logofull.png"));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), 
                                    Image.SCALE_DEFAULT));
        lblImagen.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        IniciarSesionPanel = new javax.swing.JPanel();
        IniciarSesionbtn = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        IngreUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblContraseña = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtRegistrarse = new javax.swing.JTextField();
        IngreContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        PanelPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setText("Logo");
        PanelPrincipal.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 270, 120));

        lblMinimizar.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar.setText("−");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseExited(evt);
            }
        });
        PanelPrincipal.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 50, 50));

        lblCerrar.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setText("X");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarMouseExited(evt);
            }
        });
        PanelPrincipal.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 10, 50, 50));

        IniciarSesionPanel.setBackground(new java.awt.Color(255, 0, 51));

        IniciarSesionbtn.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        IniciarSesionbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IniciarSesionbtn.setText("Iniciar Sesion");
        IniciarSesionbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IniciarSesionbtn.setFocusable(false);
        IniciarSesionbtn.setMaximumSize(new java.awt.Dimension(32767, 32767));
        IniciarSesionbtn.setMinimumSize(new java.awt.Dimension(100, 100));
        IniciarSesionbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarSesionbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout IniciarSesionPanelLayout = new javax.swing.GroupLayout(IniciarSesionPanel);
        IniciarSesionPanel.setLayout(IniciarSesionPanelLayout);
        IniciarSesionPanelLayout.setHorizontalGroup(
            IniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IniciarSesionPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IniciarSesionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        IniciarSesionPanelLayout.setVerticalGroup(
            IniciarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IniciarSesionPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IniciarSesionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelPrincipal.add(IniciarSesionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario");
        PanelPrincipal.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 100, 30));

        IngreUsuario.setBackground(new java.awt.Color(0, 0, 0));
        IngreUsuario.setForeground(new java.awt.Color(102, 102, 102));
        IngreUsuario.setText("Ingrese su nombre de usuario");
        IngreUsuario.setBorder(null);
        IngreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IngreUsuarioMousePressed(evt);
            }
        });
        PanelPrincipal.add(IngreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 300, 20));
        PanelPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 300, -1));

        lblContraseña.setBackground(new java.awt.Color(0, 0, 0));
        lblContraseña.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña.setText("Contraseña");
        PanelPrincipal.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 110, 30));
        PanelPrincipal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 300, -1));

        txtRegistrarse.setEditable(false);
        txtRegistrarse.setBackground(new java.awt.Color(0, 0, 0));
        txtRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        txtRegistrarse.setText("¿Aún no tienes cuenta? ¡Registrate!");
        txtRegistrarse.setBorder(null);
        txtRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRegistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtRegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtRegistrarseMouseExited(evt);
            }
        });
        PanelPrincipal.add(txtRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        IngreContraseña.setBackground(new java.awt.Color(0, 0, 0));
        IngreContraseña.setForeground(new java.awt.Color(102, 102, 102));
        IngreContraseña.setText("************");
        IngreContraseña.setBorder(null);
        IngreContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IngreContraseñaMousePressed(evt);
            }
        });
        PanelPrincipal.add(IngreContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseEntered
        //Pone las letras en color rojo
        lblCerrar.setForeground(Color.red);
    }//GEN-LAST:event_lblCerrarMouseEntered

    private void lblCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseExited
        //Pone las letras en color blanco
        lblCerrar.setForeground(Color.white);
    }//GEN-LAST:event_lblCerrarMouseExited

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        //Cierra el programa
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        //Minimiza la ventana
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseEntered
        //Pone las letras en color gris
        lblMinimizar.setForeground(Color.gray);
    }//GEN-LAST:event_lblMinimizarMouseEntered

    private void lblMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseExited
        //Pone las letras en color blanco
        lblMinimizar.setForeground(Color.white);
    }//GEN-LAST:event_lblMinimizarMouseExited

    private void IniciarSesionbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesionbtnMouseClicked
        //Permite ejecutar sentencias en el server de SQL
        PreparedStatement ps = null;
        
        //Validación de datos para inicio de sesión
        try {
            //Conecta a la base de datos
            connect = DriverManager.getConnection(url);
        } catch (Exception x) {
            JOptionPane.showMessageDialog(null, x.getMessage().toString());
        }
        //Almacena los resultados de la consulta
        ResultSet rs = null;
        String correo = IngreUsuario.getText();
        String pass = String.valueOf(IngreContraseña.getPassword());
        if (correo.equals("") || pass.equals("")) {
            JOptionPane.showMessageDialog(this, "Uno o mas campos estan vacios, intente de nuevo.");
        } else {
            try {
                ps = connect.prepareStatement("select correo, Password, Rol from Usuarios where correo = '" + correo
                        + "' and Password = '" + pass + "' AND (Rol = 'Profesor' or 'profesor')");
                rs = ps.executeQuery();

                //Si las credenciales son correctas y es profesor se ejecuta esta ventana
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Sesion iniciada correctamente");
                    Diseño dis = new Diseño();
                    dis.Usuario1.setText(correo);
                    dis.Rol1.setText("Profesor");
                    dis.setVisible(true);
                    this.dispose();

                } else {
                    //Si las credenciales son correctas y es estudiante se ejecuta esto
                    ps = connect.prepareStatement("select correo, Password, Rol from Usuarios where correo = '" + correo
                            + "' and Password = '" + pass + "' AND (Rol = 'Estudiante' or 'estudiante')");

                    rs = ps.executeQuery();
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(this, "Sesion iniciada correctamente");
                        DiseñoParaEstudiante estu = new DiseñoParaEstudiante();
                        estu.Usuario1.setText(correo);
                        estu.Rol1.setText("Estudiante");
                        estu.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Credenciales incorrectas, intente otra vez");
                        intentos++;
                    }
                    if (intentos == 3) {
                        JOptionPane.showMessageDialog(rootPane, "Excediste el límites de intentos");
                        Registrarse Registro = new Registrarse();
                        Registro.setVisible(true);
                        this.dispose();
                    }
                }
            } catch (SQLException e) {
                System.err.println(e.toString());
                JOptionPane.showMessageDialog(this, "Ocurrio un error inesperado \n Intente otra vez.");
            } finally {
                try {
                    if (ps != null) {
                        ps.close();
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e);

                }
            }
        }


    }//GEN-LAST:event_IniciarSesionbtnMouseClicked

    private void txtRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRegistrarseMouseEntered
        //El texto cambiará a color azul en el momento que el curso esté encima del mismo.
        txtRegistrarse.setForeground(new Color(102, 102, 255));
    }//GEN-LAST:event_txtRegistrarseMouseEntered

    private void txtRegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRegistrarseMouseExited
        //El texto cambiará a color blanco cuando el curso ya no esté encima del mismo.
        txtRegistrarse.setForeground(Color.white);
    }//GEN-LAST:event_txtRegistrarseMouseExited

    private void IngreUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngreUsuarioMousePressed
        //Da efecto de PlaceHolder a la caja de texto.
        if (IngreUsuario.getText().equals("Ingrese su nombre de usuario")) {
            IngreUsuario.setText("");
            IngreUsuario.setForeground(Color.white);
        }
        if (String.valueOf(IngreContraseña.getPassword()).isEmpty()) {
            IngreContraseña.setText("************");
            IngreContraseña.setForeground(new Color(102, 102, 102));
        }
            

    }//GEN-LAST:event_IngreUsuarioMousePressed
    //Variables de tipo entero donde se almacenará la posición del mouse.
    int xx, xy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        //Obtendrá la posición X e Y del mouse cuando la presionemos.
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        //Obtendrá la posición X e Y de la pantalla
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        //Restar la posción del a pantalla con la posición del mouse.
        setLocation(x - xx, y - xy);

    }//GEN-LAST:event_formMouseDragged

    private void txtRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRegistrarseMouseClicked
        //Instanciamos el frame donde se encuentra la pantalla de registro.
        Registrarse registro = new Registrarse();
        //Hacemos visible la pantalla de registro.
        registro.setVisible(true);
        //Cerramos la pantalla de Login
        this.dispose();
    }//GEN-LAST:event_txtRegistrarseMouseClicked

    private void IngreContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngreContraseñaMousePressed
        //Da efecto de PlaceHolder a la caja de texto.
        if (String.valueOf(IngreContraseña.getPassword()).equals("************")) {
            IngreContraseña.setText("");
            IngreContraseña.setForeground(Color.white);
        }
        if (IngreUsuario.getText().isEmpty()) {
            IngreUsuario.setText("Ingrese su nombre de usuario");
            IngreUsuario.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_IngreContraseñaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField IngreContraseña;
    private javax.swing.JTextField IngreUsuario;
    private javax.swing.JPanel IniciarSesionPanel;
    private javax.swing.JLabel IniciarSesionbtn;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtRegistrarse;
    // End of variables declaration//GEN-END:variables
}
