/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Diseño;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.commons.validator.routines.EmailValidator;

/**
 *
 * @author frany
 */
public class Registrarse extends javax.swing.JFrame {
    //Objetos necesarios para la conexión a la base de datos
    //En este objeto se almacena la ubicación del archivo donde se encuetra la base de datos.
    String url = "jdbc:sqlite:C:\\Diseño\\src\\BaseDeDatos\\BDProyecto.db";
    //Objeto necesario para realizar la conexión.
    Connection connect;

    public Registrarse() {
        //Quitar la botonera superior que traen por defectos las ventanas.
        setUndecorated(true);

        initComponents();
        //Hace que el Jframe inicie en el centro de la pantalla
        this.setLocationRelativeTo(this);
        //Hace que el panel sea transparente
        PanelSecundario.setBackground(new Color(0, 0, 0, 200));
        //Sirve para poder ajustar el tamaño de la imagen dentro de un JLabel
        ImageIcon imagen = new ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblFondo.getWidth(), lblFondo.getHeight(), Image.SCALE_DEFAULT));
        lblFondo.setIcon(icono);
        this.repaint();
        
        //Cambia el color de las letras.
        lblCorreo.setForeground(Color.white);
        lblNombre.setForeground(Color.white);
        lblApellido.setForeground(Color.white);
        lblContraseña.setForeground(Color.white);
        lblRol.setForeground(Color.white);
        lblTitulo.setForeground(new Color(0, 0, 255));
        lblTitulo2.setForeground(new Color(0, 0, 255));
        
        //Reducir la opacidad.
        txtNombre.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtCorreo.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtApellido.setBackground(new java.awt.Color(0, 0, 0, 1));
        psContraseña.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtInicioSesion.setBackground(new java.awt.Color(0, 0, 0, 1));
        CBSeleccionarRol.setBackground(new java.awt.Color(0, 0, 0, 1));
        
        //Hace invisible el label
        lblAviso.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        psContraseña = new javax.swing.JPasswordField();
        txtInicioSesion = new javax.swing.JTextField();
        lblRol = new javax.swing.JLabel();
        CBSeleccionarRol = new javax.swing.JComboBox<>();
        lblAviso = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JPanel();
        lblRegistrarse = new javax.swing.JLabel();
        PanelSecundario = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCerrar.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setText("X");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarMouseExited(evt);
            }
        });
        PanelPrincipal.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        lblMinimizar.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar.setText("−");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseExited(evt);
            }
        });
        PanelPrincipal.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, 30));

        lblCorreo.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        lblCorreo.setText("Correo:");
        PanelPrincipal.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Roboto Condensed", 1, 48)); // NOI18N
        lblTitulo.setText("Bienvenidos");
        PanelPrincipal.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        lblTitulo2.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        lblTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo2.setText("−Registrate−");
        PanelPrincipal.add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        lblNombre.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        lblNombre.setText("Nombre:");
        PanelPrincipal.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        lblApellido.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        lblApellido.setText("Apellido:");
        PanelPrincipal.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        lblContraseña.setText("Contraseña:");
        PanelPrincipal.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        txtApellido.setForeground(new java.awt.Color(102, 102, 102));
        txtApellido.setText("Apellido");
        txtApellido.setBorder(null);
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoMousePressed(evt);
            }
        });
        PanelPrincipal.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 240, -1));

        txtCorreo.setForeground(new java.awt.Color(102, 102, 102));
        txtCorreo.setText("Correo");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCorreoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoKeyReleased(evt);
            }
        });
        PanelPrincipal.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 240, -1));

        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setText("Nombre");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        PanelPrincipal.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 240, -1));
        PanelPrincipal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 240, -1));
        PanelPrincipal.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 240, -1));
        PanelPrincipal.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 240, -1));
        PanelPrincipal.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 240, -1));

        psContraseña.setForeground(new java.awt.Color(102, 102, 102));
        psContraseña.setText("***************");
        psContraseña.setBorder(null);
        psContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                psContraseñaMousePressed(evt);
            }
        });
        PanelPrincipal.add(psContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 240, -1));

        txtInicioSesion.setEditable(false);
        txtInicioSesion.setBackground(new java.awt.Color(255, 255, 255));
        txtInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        txtInicioSesion.setText(" ¡Ya tengo una cuenta!");
        txtInicioSesion.setBorder(null);
        txtInicioSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtInicioSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtInicioSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtInicioSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtInicioSesionMouseExited(evt);
            }
        });
        PanelPrincipal.add(txtInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 670, -1, -1));

        lblRol.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        lblRol.setText("Rol:");
        PanelPrincipal.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 120, 30));

        CBSeleccionarRol.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CBSeleccionarRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Profesor", " " }));
        CBSeleccionarRol.setBorder(null);
        PanelPrincipal.add(CBSeleccionarRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 150, -1));

        lblAviso.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        lblAviso.setForeground(java.awt.Color.red);
        lblAviso.setText("Correo invalido");
        PanelPrincipal.add(lblAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        btnRegistrarse.setBackground(new java.awt.Color(204, 204, 204));

        lblRegistrarse.setBackground(new java.awt.Color(255, 255, 255));
        lblRegistrarse.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        lblRegistrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrarse.setText("Registrar");
        lblRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRegistrarseLayout = new javax.swing.GroupLayout(btnRegistrarse);
        btnRegistrarse.setLayout(btnRegistrarseLayout);
        btnRegistrarseLayout.setHorizontalGroup(
            btnRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnRegistrarseLayout.setVerticalGroup(
            btnRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        PanelPrincipal.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 180, 40));

        javax.swing.GroupLayout PanelSecundarioLayout = new javax.swing.GroupLayout(PanelSecundario);
        PanelSecundario.setLayout(PanelSecundarioLayout);
        PanelSecundarioLayout.setHorizontalGroup(
            PanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        PanelSecundarioLayout.setVerticalGroup(
            PanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        PanelPrincipal.add(PanelSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 720));
        PanelPrincipal.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseEntered
        //Cambia el color del texto a rojo
        lblCerrar.setForeground(Color.red);
    }//GEN-LAST:event_lblCerrarMouseEntered

    private void lblCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseExited
        //Cambia el color del texto a blanco
        lblCerrar.setForeground(Color.white);
        //Reduce la opacidad del fondo
        lblCerrar.setBackground(new Color(0, 0, 0, 100));
    }//GEN-LAST:event_lblCerrarMouseExited

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        //Cierra el programa
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseEntered
        //Cambia el color del boton a gris cuando el mouse se posa encima.
        lblMinimizar.setForeground(Color.gray);
    }//GEN-LAST:event_lblMinimizarMouseEntered

    private void lblMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseExited
        //Cambia el color del boton a blanco cuando el mouse ya no está encima
        lblMinimizar.setForeground(Color.white);
    }//GEN-LAST:event_lblMinimizarMouseExited

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        //Minimiza la ventana
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void txtCorreoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseEntered

    }//GEN-LAST:event_txtCorreoMouseEntered

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        //Da efecto de PlaceHolder a la caja de texto.
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(new Color(102, 102, 102));
        }
        if (txtNombre.getText().equals("Nombre")) {
            txtNombre.setText("");
            txtNombre.setForeground(Color.white);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("Apellido");
            txtApellido.setForeground(new Color(102, 102, 102));
        }
        if (String.valueOf(psContraseña.getPassword()).isEmpty()) {
            psContraseña.setText("***************");
            psContraseña.setForeground(new Color(102, 102, 102));
        }
        if (txtCorreo.getText().equals("Correo")) {
            lblAviso.setVisible(false);
        }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        //Da efecto de PlaceHolder a la caja de texto.
        if (txtCorreo.getText().equals("Correo")) {
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.white);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Nombre");
            txtNombre.setForeground(new Color(102, 102, 102));
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("Apellido");
            txtApellido.setForeground(new Color(102, 102, 102));
        }
        if (String.valueOf(psContraseña.getPassword()).isEmpty()) {
            psContraseña.setText("***************");
            psContraseña.setForeground(new Color(102, 102, 102));
        }
        if (txtCorreo.getText().equals("Correo")) {
            lblAviso.setVisible(false);
        }

    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMousePressed
        //Da efecto de PlaceHolder a la caja de texto.
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(new Color(102, 102, 102));
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Nombre");
            txtNombre.setForeground(new Color(102, 102, 102));
        }
        if (txtApellido.getText().equals("Apellido")) {
            txtApellido.setText("");
            txtApellido.setForeground(Color.white);
        }
        if (String.valueOf(psContraseña.getPassword()).isEmpty()) {
            psContraseña.setText("***************");
            psContraseña.setForeground(new Color(102, 102, 102));
        }
        if (txtCorreo.getText().equals("Correo")) {
            lblAviso.setVisible(false);
        }
    }//GEN-LAST:event_txtApellidoMousePressed

    private void psContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psContraseñaMousePressed
        //Da efecto de PlaceHolder a la caja de texto.
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("Correo");
            txtCorreo.setForeground(new Color(102, 102, 102));
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Nombre");
            txtNombre.setForeground(new Color(102, 102, 102));
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("Apellido");
            txtApellido.setForeground(new Color(102, 102, 102));
        }
        if (String.valueOf(psContraseña.getPassword()).equals("***************")) {
            psContraseña.setText("");
            psContraseña.setForeground(Color.white);
        }
        if (txtCorreo.getText().equals("Correo")) {
            lblAviso.setVisible(false);
        }
    }//GEN-LAST:event_psContraseñaMousePressed

    private void lblRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseEntered
        //Cambia el color de boton a azul cuando el mouse se posa encima
        btnRegistrarse.setBackground(new Color(102, 102, 255));
    }//GEN-LAST:event_lblRegistrarseMouseEntered

    private void lblRegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseExited
        //Cambia el color del boton a gris cuando el mouse no se encuentra encima
        btnRegistrarse.setBackground(new Color(204, 204, 204));

    }//GEN-LAST:event_lblRegistrarseMouseExited

    private void txtInicioSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInicioSesionMouseClicked
        //Instancia el frame del Login
        Login log = new Login();
        //Hace el login visible
        log.setVisible(true);
        //Cierra esta ventana
        this.dispose();
    }//GEN-LAST:event_txtInicioSesionMouseClicked

    private void txtInicioSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInicioSesionMouseEntered
        //El texto cambiará a color azul en el momento que el curso esté encima del mismo.
        txtInicioSesion.setForeground(new Color(102, 102, 255));
    }//GEN-LAST:event_txtInicioSesionMouseEntered

    private void txtInicioSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInicioSesionMouseExited
        //El texto cambiará a color blanco cuando el curso ya no esté encima del mismo.
        txtInicioSesion.setForeground(Color.white);
    }//GEN-LAST:event_txtInicioSesionMouseExited
 
                     /*Arrastrar la ventana por toda la pantalla*/   
//Variables de tipo entero donde se almacenará la posición del mouse.
    int xx, xy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        //Obtendrá la posición X e Y del mouse cuando la presionemos.
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        //Obtendrá la posición X e Y de la pantalla.
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        //Restar la posción del a pantalla con la posición del mouse.
        setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

                      /*Registro de nuevo usuario*/
    private void lblRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseClicked
        //Instaciamos el frame o pantalla del Login.
        Login log = new Login();
        //Hacemos la llamada al metodo que realiza la conexión.
        conectar();
        //Permite ejecutar sentencias en el server de SQL
        PreparedStatement ps = null;
        if (txtCorreo.getText().toString().equals("Correo") || txtNombre.getText().toString().equals("Nombre")
                || txtApellido.getText().toString().equals("Apellido")
                || String.valueOf(psContraseña.getPassword()).equals("***************")) {

            JOptionPane.showMessageDialog(this, "Uno o mas campos estan vacios, intente otra vez.");

        } else {
            if (lblAviso.isVisible() == true) {
                JOptionPane.showMessageDialog(null, "Escriba el correo correctamente");
            } else {
                try {

                    ps = connect.prepareStatement("INSERT INTO Usuarios (nombre, apellido, correo, rol, password) VALUES (?,?,?,?,?)");
                    ps.setString(3, txtCorreo.getText());
                    ps.setString(1, txtNombre.getText());
                    ps.setString(2, txtApellido.getText());
                    ps.setString(5, String.valueOf(psContraseña.getPassword()));
                    if (CBSeleccionarRol.getSelectedIndex() == 0) {
                        //ps = connect.prepareStatement("INSERT INTO Usuarios (rol) VALUES (?)"); 
                        ps.setString(4, "Estudiante");
                    } else {
                        //ps = connect.prepareStatement("INSERT INTO Usuarios (rol) VALUES (?)"); 
                        ps.setString(4, "Profesor");
                        //ps.setInt(4, CBSeleccionarRol.getSelectedIndex());
                    }
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "Registro realizado con exito.");
                } catch (SQLException ex) {

                    JOptionPane.showMessageDialog(rootPane, "Error en la consulta: " + ex);
                } finally {
                    try {
                        if (ps != null) {
                            ps.close();
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e);
                    }
                }
            }
            if (lblAviso.isValid() == false) {
                log.setVisible(true);
                this.dispose();
            }
        }


    }//GEN-LAST:event_lblRegistrarseMouseClicked

                       /*Validación de correo*/
    private void txtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyReleased
        if (EmailValidator.getInstance().isValid(txtCorreo.getText())) {

            lblAviso.setVisible(false);

        } else {

            lblAviso.setVisible(true);
        }
        if (txtCorreo.getText().isEmpty()) {
            lblAviso.setVisible(false);
        }
    }//GEN-LAST:event_txtCorreoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBSeleccionarRol;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelSecundario;
    private javax.swing.JPanel btnRegistrarse;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegistrarse;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JPasswordField psContraseña;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtInicioSesion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
    
    //Conexión a la base de datos
    public Connection conectar() {
        try {
            connect = DriverManager.getConnection(url);

        } catch (Exception x) {
            JOptionPane.showMessageDialog(null, x.getMessage().toString());

        }
        return connect;
    }
}
